XDG_CACHE_HOME=$HOME/.cache
XDG_CONFIG_HOME=$HOME/.config
XDG_DATA_HOME=$HOME/.local/share

ZDOTDIR=${XDG_CONFIG_HOME}/zsh
ZSH_CACHE_DIR=${XDG_CACHE_HOME}/zsh

skip_global_compinit=1

export XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
export ZDOTDIR ZSH_CACHE_DIR

source $ZDOTDIR/env/env.zsh
